---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: servicex
  namespace: sthapa
spec:
  interval: 1m
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: servicex
  validation: client

